# Generated by Django 4.1 on 2022-08-26 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetOwner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('gender', models.CharField(max_length=16, verbose_name='性别')),
                ('phone', models.CharField(max_length=128, unique=True, verbose_name='电话号码')),
                ('address', models.CharField(max_length=512, verbose_name='家庭住址')),
            ],
            options={
                'verbose_name': '宠物主信息',
                'verbose_name_plural': '宠物主信息',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('gender', models.CharField(max_length=16, verbose_name='性别')),
                ('phone', models.CharField(max_length=128, unique=True, verbose_name='电话号码')),
                ('address', models.CharField(max_length=512, verbose_name='家庭住址')),
                ('home_town', models.CharField(max_length=128, verbose_name='籍贯')),
                ('id_number', models.CharField(max_length=64, verbose_name='身份证号')),
            ],
            options={
                'verbose_name': '员工信息',
                'verbose_name_plural': '员工信息',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='名字')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('species', models.CharField(max_length=16, verbose_name='物种')),
                ('deposit_start_time', models.DateTimeField(auto_now=True, verbose_name='寄存开始时间')),
                ('deposit_end_time', models.DateTimeField(blank=True, null=True, verbose_name='寄存结束时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_owner', to='pet.petowner', verbose_name='宠物主')),
                ('receive_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_staff', to='pet.staff', verbose_name='接收员工')),
            ],
            options={
                'verbose_name': '宠物信息',
                'verbose_name_plural': '宠物信息',
            },
        ),
    ]
