# Generated by Django 4.1 on 2022-08-26 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='receive_staff',
        ),
    ]
