# Generated by Django 4.1 on 2022-08-26 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_remove_pet_receive_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='receive_staff',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pet_staff', to='pet.staff', verbose_name='接收员工'),
        ),
    ]
