# Generated by Django 4.1 on 2022-08-26 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_pet_receive_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=64, unique=True, verbose_name='订单号')),
                ('amount', models.FloatField(default=0.0, verbose_name='费用')),
                ('description', models.TextField(default='-', verbose_name='记录')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_order', to='pet.pet', verbose_name='消费宠物')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_order', to='pet.staff', verbose_name='操作员工')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
    ]
