# Generated by Django 4.1 on 2022-08-26 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='资产名称')),
                ('purchase_date', models.DateTimeField(verbose_name='进货时间')),
                ('amount', models.FloatField(default=0, verbose_name='单价')),
                ('quantity', models.FloatField(default=0, verbose_name='数量')),
                ('description', models.TextField(default='-', verbose_name='资产描述')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assets', to='pet.staff', verbose_name='操作员工')),
            ],
            options={
                'verbose_name': '资产',
                'verbose_name_plural': '资产',
            },
        ),
    ]
