# Generated by Django 4.1 on 2022-09-10 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='订单生成时间'),
        ),
    ]
