# Generated by Django 4.1 on 2022-08-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTurnover',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('daily', models.DateField(verbose_name='日期')),
                ('turnover', models.FloatField(verbose_name='营业额')),
            ],
            options={
                'verbose_name': '日营业额',
                'verbose_name_plural': '日营业额',
            },
        ),
        migrations.CreateModel(
            name='MonthlyTurnover',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monthly', models.CharField(max_length=12, verbose_name='月份')),
                ('turnover', models.FloatField(verbose_name='营业额')),
            ],
            options={
                'verbose_name': '月营业额',
                'verbose_name_plural': '月营业额',
            },
        ),
        migrations.CreateModel(
            name='TotalTurnover',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('turnover', models.FloatField(verbose_name='营业额')),
            ],
            options={
                'verbose_name': '总营业额',
                'verbose_name_plural': '总营业额',
            },
        ),
        migrations.CreateModel(
            name='YearTurnover',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=12, verbose_name='年份')),
                ('turnover', models.FloatField(verbose_name='营业额')),
            ],
            options={
                'verbose_name': '年营业额',
                'verbose_name_plural': '年营业额',
            },
        ),
    ]
